### ISSUE TITLE
Import not complete, some messages missing depending on phone number format

### ISSUE THREAD

**Issue by dnfoo** [tmo1/sms-ie#205] opened 2024-08-24 14:27 UTC
As hinted [here](https://github.com/tmo1/sms-ie/issues/128#issuecomment-2179301355) I can confirm that messages containing spaces in the "address" field are not imported by the current version 2.4.0.
For me this was quite a big issue, as lots of messages had their addresses formatted like "0123 4567890".

I'm submitting it as a separate issue so people can find it easier via the search function.

Here's the workaround that worked for me: 
- Extract messages.ndjson for the .zip file created by the backup function
- Search and replace with a matching regex. I used search for ([0-9]{3,6}) ([0-9]{6,10}) and replace by \1\2 in xed.
- Save the file and zip it again together with the "data" folder from the original zip.
- Import this newly created zip file

Would love to see this fixed in an upcoming version.

**Comment by tmo1** [comment] 2024-08-30 02:41
Duplicate of #159 

The main discussion of this problem is in issue #159, beginning [here](https://github.com/tmo1/sms-ie/issues/159#issuecomment-2169712551). I hope to push a fix within a couple of days.

**Comment by tmo1** [comment] 2024-08-30 02:41
Duplicate of #159.

**Closed by tmo1** 2024-08-30 02:41 UTC
Labels: bug
