### ISSUE TITLE
Importing contacts requires permission to write Contacts

### ISSUE THREAD

**Issue by a-l-n** [tmo1/sms-ie#70] opened 2022-11-06 12:08 UTC
Hi,

Sorry, I have to create a new issue, as I can't re-open https://github.com/tmo1/sms-ie/issues/69

Please see my note to https://github.com/tmo1/sms-ie/issues/69 :

Hi,

Thank you for your reply.

Since the latest release I could find is 1.5.1 (https://github.com/tmo1/sms-ie/releases), and your commit is after the release of 1.5.1, I tried building with "gradlew assembleDebug" (as per the Installation Readme). I've cloned this repo, installed gradle, ran ./gradlew assembleDebug from the root of the cloned repo and I started getting build errors - first being about missing the ANDROID_HOME environment variable in local.properties, which I defined (and created the directory), then the build failed because I need to accept SDK licence agreements and install the Android Studio SDK Manager.

At this stage, I was wondering if it's possible to get the apk file including your changes from somewhere (so I can just install and test the functionality)?

I'm afraid trying to build the file myself, might lead me down a rabbit hole, spending a lot of time just configuring the build environment.

So, if it's possible, could I please grab the apk build containing your changes from somewhere? or I can wait for the new release if a new release is planned for the near future.

Thanks again!

**Comment by tmo1** [comment] 2022-11-06 12:56
Duplicate of #69

**Closed by tmo1** 2022-11-06 12:56 UTC
