### ISSUE TITLE
Scheduled export only works once 

### ISSUE THREAD

**Issue by Myslippersreek** [tmo1/sms-ie#175] opened 2024-03-27 13:01 UTC
Hi,

Thanks very much for a very useful app. It has been very helpful to me. 

I just wanted to raise one issue I've found: whilst the scheduled export works, it only does so once. After that, exports stop occurring. I'm not sure if there is a setting I have overlooked, or a broader problem?

Thanks again,

MSR

**Comment by tmo1** [comment] 2024-03-27 16:58
> Thanks very much for a very useful app. It has been very helpful to me.

You're very welcome! I'm glad you found the app useful.

> whilst the scheduled export works, it only does so once. After that, exports stop occurring.

One possibility is that the export job is being terminated early (e.g., by [this issue](https://github.com/tmo1/sms-ie/issues/129)). The way the scheduling works is that an export job is initially scheduled to run once at the time specified by the user. When the job finishes, the app then schedules a new export job for the same time (to be run the next day). If an export job is terminated early, the rescheduling will never run.

What Android and app version are you running? Have you disabled battery optimizations in the app settings? Please provide a logcat of a scheduled job running so we can check whether the jobs are being terminated for some reason.

**Comment by tmo1** [comment] 2024-05-15 11:51
Closing due to submitter unresponsiveness; feel free to reopen with the requested information if the problem persists.

**Closed by tmo1** 2024-05-15 11:51 UTC

**Comment by mooreye** [comment] 2024-11-13 19:43
I'm experiencing delayed exports. Sometimes it will not fire until I unlock the screen despite battery optimization being disabled for the app (allow background usage). It seems Android is too eager to throttle background apps?

**Comment by tmo1** [comment] 2024-11-17 17:14
> I'm experiencing delayed exports. Sometimes it will not fire until I unlock the screen despite battery optimization being disabled for the app (allow background usage). It seems Android is too eager to throttle background apps?

Please open a new issue for this, although there's not much I can do insofar as I can't reproduce the problem.
