### ISSUE TITLE
Error on sms import

### ISSUE THREAD

**Issue by jonnieey** [tmo1/sms-ie#206] opened 2024-08-26 20:05 UTC
Android version: 13, xiaomi hyperos
sms ie version: 2.4.0

![Screenshot_2024-08-26-18-30-00-371_com.github.tmo1.sms_ie.jpg](https://github.com/user-attachments/assets/8962adcf-4fc0-417b-ac7a-a359a60b2e8c)

**Comment by tmo1** [comment] 2024-08-30 14:57
Duplicate of #103

**Comment by tmo1** [comment] 2024-08-30 14:57
https://github.com/tmo1/sms-ie#miui

**Closed by tmo1** 2024-08-30 14:57 UTC
