### ISSUE TITLE
Crash at scheduled export at Nextcloud

### ISSUE THREAD

**Issue by thanasistrisp** [tmo1/sms-ie#49] opened 2022-08-18 15:45 UTC
When manually export no crash encountered. However, when I try to schedule export it crashes. I use android 11 and I try to save at **nextcloud** location from system picker. The error message is `Export unsuccessful - see logcat for more details`. However, when I choose a folder inside internal storage works perfectly.

**Comment by tmo1** [comment] 2022-08-19 02:59
Thank you for reporting this. Would you please [post a logcat](https://github.com/tmo1/sms-ie#bugs-feature-requests-and-other-issues), as per the error message?

**Comment by tmo1** [comment] 2022-08-19 18:54
Thank you - I'll look into this.

In my testing, I only use internal storage, and although I have my own Nextcloud instance, I don't use it with Android, so I have little experience with Android and cloud storage.

**Comment by tmo1** [comment] 2022-08-23 12:15
> The weird is that the error happens only at export stage. At manual method from main menu it works correctly with nextoud.

The code flow for scheduled export is considerably different from that of direct export. In particular, when scheduling, the user selects a directory, not a file, and SMS Import / Export later tries to create a file in that directory, as opposed to direct export, where the user selects an output file directly. There have apparently been many problems similar to yours with using Nextcloud as an export / backup destination: see [here](https://github.com/OpenTracksApp/OpenTracks/issues/516), [here](https://github.com/seedvault-app/seedvault/issues/96), [here](https://github.com/nextcloud/android/issues/303), [here](https://github.com/nextcloud/android/issues/7350), [here](https://github.com/nextcloud/android/issues/8201), [here](https://github.com/nextcloud/android/issues/8028), [here](https://help.nextcloud.com/t/storage-access-framework-cannot-create-file-in-cloud-folder-selected-with-action-open-document-tree/66482), and [here](https://stackoverflow.com/questions/59392740/storage-access-framework-cannot-create-file-in-cloud-folder-selected-with-acti).

At this point, I'm not sure whether your reported problem is with SMS Import / Export or Nextcloud; we're going to continue the discussion at Nextcloud's issue tracker [here](https://github.com/nextcloud/android/issues/8201).

**Comment by tamas646** [comment] 2022-08-24 15:35
Exactly the same problem here.

**SMS Import / Export version:** 1.4.2
**Nextcloud App version:** 3.21.0 (F-Droid version)
**Nextcloud server version:** 24.0.4

Logcat for scheduled export:
```logcat
[08-24 17:10:00.172 26197:13406 D/DocumentsStorageProvider]
createDocument(), id=66224fecb350e86aa7ea9da32c482c9b/378

[08-24 17:10:00.206 26197:13406 D/OwnCloudClient #0]
REQUEST PUT /remote.php/dav/files/username//some/remote/path/messages-2022-08-24.json

[08-24 17:10:00.211 26197:13406 E/DocumentsStorageProvider]
RemoteOperationResult{mSuccess=false, mHttpCode=-1, mHttpPhrase='null', mException=android.os.NetworkOnMainThreadException, mCode=HOST_NOT_AVAILABLE, message='null', getLogMessage='Unexpected exception'}

[08-24 17:10:00.212 26197:13406 E/DatabaseUtils]
Writing exception to parcel
android.os.ParcelableException: java.io.FileNotFoundException: Failed to upload document with path /some/remote/path/messages-2022-08-24.json
	at android.provider.DocumentsProvider.call(DocumentsProvider.java:1080)
	at android.content.ContentProvider.call(ContentProvider.java:2464)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:512)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
Caused by: java.io.FileNotFoundException: Failed to upload document with path /some/remote/path/messages-2022-08-24.json
	at com.owncloud.android.providers.DocumentsStorageProvider.createFile(DocumentsStorageProvider.java:567)
	at com.owncloud.android.providers.DocumentsStorageProvider.createDocument(DocumentsStorageProvider.java:486)
	at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:1139)
	at android.provider.DocumentsProvider.call(DocumentsProvider.java:1078)
	... 5 more

[08-24 17:10:00.225 26197:13406 D/DocumentsStorageProvider]
createDocument(), id=66224fecb350e86aa7ea9da32c482c9b/378

[08-24 17:10:00.265 26197:13406 D/OwnCloudClient #0]
REQUEST PUT /remote.php/dav/files/username//some/remote/path/call-logs-2022-08-24.json

[08-24 17:10:00.266 26197:13406 D/AdvancedSslSocketFactory]
Creating SSL Socket with remote mydomain.example:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@982e166

[08-24 17:10:00.267 26197:13406 D/AdvancedSslSocketFactory]
 ... with connection timeout 60000 and socket timeout 60000

[08-24 17:10:00.269 26197:13406 E/DocumentsStorageProvider]
RemoteOperationResult{mSuccess=false, mHttpCode=-1, mHttpPhrase='null', mException=android.os.NetworkOnMainThreadException, mCode=HOST_NOT_AVAILABLE, message='null', getLogMessage='Unexpected exception'}

[08-24 17:10:00.269 26197:13406 E/DatabaseUtils]
Writing exception to parcel
android.os.ParcelableException: java.io.FileNotFoundException: Failed to upload document with path /some/remote/path/call-logs-2022-08-24.json
	at android.provider.DocumentsProvider.call(DocumentsProvider.java:1080)
	at android.content.ContentProvider.call(ContentProvider.java:2464)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:512)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
Caused by: java.io.FileNotFoundException: Failed to upload document with path /some/remote/path/call-logs-2022-08-24.json
	at com.owncloud.android.providers.DocumentsStorageProvider.createFile(DocumentsStorageProvider.java:567)
	at com.owncloud.android.providers.DocumentsStorageProvider.createDocument(DocumentsStorageProvider.java:486)
	at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:1139)
	at android.provider.DocumentsProvider.call(DocumentsProvider.java:1078)
	... 5 more
```

**Comment by tmo1** [comment] 2022-08-25 03:43
> Exactly the same problem here.

You're getting a `NetworkOnMainThreadException`, which does not appear in @thanasistrisp's logcat. As I note [here](https://github.com/nextcloud/android/issues/8201#issuecomment-1225607001), I got that error when trying to reproduce @thanasistrisp's crash, and I fixed it [here](https://github.com/tmo1/sms-ie/commit/25aa9ddfa06ad54d264acb19b9983760c190d288).

**Comment by tmo1** [comment] 2022-08-25 03:49
@thanasistrisp: As per my previous message and [here](https://github.com/nextcloud/android/issues/8201#issuecomment-1225607001), with the latest commit to SMS Import / Export, exporting to Nextcloud, both manually and via scheduling, works correctly in my testing, so I'm closing this issue. If you continue to see the problem you originally reported, and you can reproduce it using the latest SMS Import / Export code and a current version of Nextcloud and its Android app, please update this report or [the Nextcloud one I mentioned above](https://github.com/nextcloud/android/issues/8201).

**Closed by tmo1** 2022-08-25 03:49 UTC
Labels: bug

**Comment by tmo1** [comment] 2022-08-25 19:29
> OK great. So will you update the app on fdroid?

If I don't encounter any further problems or regressions, I'll try to release a version with the fix tomorrow, at which point you'll be able to download the APK from Github. F-Droid should have the new version within a few days.

**Comment by tamas646** [comment] 2022-08-25 20:43
@thanasistrisp based on the conversations I guess it's not a Nextcloud related problem (but correct me if I'm wrong), so a pull request for Nextcloud app would be pointless. All other apps will have to make it's own (and maybe different) fix in their code.

**Comment by tmo1** [comment] 2022-08-28 04:13
>  I guess it's not a Nextcloud related problem (but correct me if I'm wrong)

Whether it is or is not a Nextcloud problem is actually an interesting question. The situation as I understand it is as follows:

- Android [discourages](https://developer.android.com/guide/background/threading) "calling long-running operations" on an application's main thread, although "long-running" is not formally defined, and this rule is not strictly enforced.
- An exception is network access, which ([in recent versions of Android](https://www.androiddesignpatterns.com/2012/06/app-force-close-honeycomb-ics.html)) is strictly forbidden on the main thread, and will [throw an exception if attempted](https://developer.android.com/reference/android/os/NetworkOnMainThreadException).
- Accordingly, I (and apparently other Android developers as well) wrote code that does the occasional simple I/O operation (such as file creation) on the main thread, since this is not typically a "long-running" operation, and not absolutely forbidden by Android. This works fine for local file access, but when the user selects a Nextcloud destination, then we have a network access on the main thread, which throws the aforementioned exception.
- Nextcloud apparently takes the position that this is not its problem, and it's the calling application's responsibility to ensure that no [Storage Access Framework (SAF)](https://developer.android.com/guide/topics/providers/document-provider) invocation, which could potentially wind up involving network access if the user selects a cloud destination such as Nextcloud, is done on the main thread. (See [this discussion](https://github.com/nextcloud/android/issues/7350), starting from [here](https://github.com/nextcloud/android/issues/7350#issuecomment-731227661).)
- It could, however, be argued that since Android does not strictly forbid SAF invocations from the main thread, it's actually SAF providers' job to avoid network access on the main thread.
- Regardless of whose responsibility it actually is, it's probably good practice to move all I/O off the main thread, and at least in our case, doing so was literally a matter of [a change of a single occurrence of `Main` to `IO`](https://github.com/tmo1/sms-ie/commit/25aa9ddfa06ad54d264acb19b9983760c190d288).
