### ISSUE TITLE
Error parsing JSON when importing call log

### ISSUE THREAD

**Issue by zopelee** [tmo1/sms-ie#210] opened 2024-09-06 06:21 UTC
Steps:
1. export call log
2. import call log with the json above
3. see the error below

Error parseing JSON:

"java.lang.IllegalArgumentException: column 'LAST_SEVEN_NUMBER' is invalid"

Software: sms-ie 2.4.0
Device: Huawei Mate 9 Pro (LON-L29)
OS: EMUI 9.0.1 (Android 9)

**Comment by tmo1** [comment] 2024-09-06 16:41
Duplicate of #185

**Comment by tmo1** [comment] 2024-09-06 16:43
> Software: sms-ie 2.4.0
> Device: Huawei Mate 9 Pro (LON-L29)
> OS: EMUI 9.0.1 (Android 9)

Does this refer to the exporting device, the importing one, or both?

Please post a (redacted) [mimimal reproducible example](https://github.com/tmo1/sms-ie#minimal-reproducible-example). Even a single typical JSON record would be useful.

**Closed** 2024-11-19 21:12 UTC
Labels: bug

**Comment by zopelee** [comment] 2025-06-09 11:57
> > Software: sms-ie 2.4.0
> > Device: Huawei Mate 9 Pro (LON-L29)
> > OS: EMUI 9.0.1 (Android 9)
> 
> Does this refer to the exporting device, the importing one, or both?
> 
both

**Comment by zopelee** [comment] 2025-06-09 12:00
> Please post a (redacted) [mimimal reproducible example](https://github.com/tmo1/sms-ie#minimal-reproducible-example). Even a single typical JSON record would be useful.

Here please [calls-log-bug.json](https://github.com/user-attachments/files/20654284/calls-log-bug.json)

**Comment by tmo1** [comment] 2025-06-09 21:32
I can't reproduce your problem - I imported the file you posted, and the import was successful, with no errors displayed.

**Comment by tmo1** [comment] 2025-06-10 17:12
Please confirm that [this build](https://github.com/tmo1/sms-ie/actions/runs/15565771319/artifacts/3298559375) fixes the problem.

**Comment by zopelee** [comment] 2025-06-12 01:59
The fix works. Thanks!

**Comment by tmo1** [comment] 2025-06-12 19:15
> The fix works. Thanks!

Thanks for confirming!
