### ISSUE TITLE
Error importing messages

### ISSUE THREAD

**Issue by DavidHenryThoreau** [tmo1/sms-ie#152] opened 2024-01-19 14:14 UTC
I've got this error on 
```
Android : 14 UKQ1.230917.001
```

```
Error importing messages

An error was encountered while importing messages :

"java.lan.illegalArgumentException: The non-sync-callers AND non-blocked-url should not specify DELETED for inserting."

See logcat for more information.
```

**Comment by tmo1** [comment] 2024-01-19 14:55
Thanks for the report. This is a known issue with MIUI ([documented in the README](https://github.com/tmo1/sms-ie#miui))  - please read the discussion [here](https://github.com/tmo1/sms-ie/issues/103), and follow-up there.

Duplicate of #103

**Comment by tmo1** [comment] 2024-01-19 14:56
Duplicate of #103

**Closed** 2024-01-19 14:56 UTC

**Comment by DavidHenryThoreau** [comment] 2024-01-27 09:14
Thanks for reply but I'm getting error.

```
jq: error (at messages.ndjson:18575): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18576): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18577): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18578): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18579): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18580): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18581): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18576): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18577): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18578): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18579): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18580): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18581): Cannot index string with string "display_name"
```

**Comment by DavidHenryThoreau** [comment] 2024-01-27 09:15
Thanks for reply but I'm getting error and messages-nnn-MIUI-stripped.json is empty

```
jq: error (at messages.ndjson:18575): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18576): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18577): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18578): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18579): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18580): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18581): Cannot index string with string "deleted"
jq: error (at messages.ndjson:18576): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18577): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18578): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18579): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18580): Cannot index string with string "display_name"
jq: error (at messages.ndjson:18581): Cannot index string with string "display_name"
```

**Comment by tmo1** [comment] 2024-01-29 01:51
Please post some of the (redacted) lines that are causing the error, and I'll take a look.

**Comment by DavidHenryThoreau** [comment] 2024-02-01 07:26
I don't have `id 18575`.
Does 18575 means line number ?

**Comment by DavidHenryThoreau** [comment] 2024-02-02 10:55
```

{"_id":"18","thread_id":"14","date":"1620739770","date_sent":"1620730823","msg_box":"1","read":"1","m_id":"148C2480-B248-71EB-8618-0050569C3D99","ct_t":"application\/vnd.wap.multipart.related","ct_l":"http:\/\/2x.orange.fr\/mmsc?XCPPKPOREREJNa","m_cls":"personal","m_type":"132","v":"18","m_size":"594830","pri":"129","tr_id":"TOTOTO","retr_st":"128","retr_txt":"1000:Ok","retr_txt_cs":"106","d_rpt":"129","locked":"0","seen":"1","timed":"0","date_ms_part":"0","deleted":"0","sync_state":"0","marker":"0","bind_id":"0","mx_status":"0","need_download":"0","out_time":"0","preview_type":"0","preview_data_ts":"0","sim_id":"1","block_type":"0","advanced_seen":"3","mx_type":"0","favorite_date":"0","text_only":"0","__sender_address":{"_id":"22","msg_id":"18","address":"+33970580490","type":"137","charset":"106","__display_name":"TTTïs"},"__recipient_addresses":[{"_id":"23","msg_id":"18","address":"+33878235890","type":"151","charset":"106","__display_name":"oi"}],"__parts":[{"_id":"40","mid":"18","seq":"-1","ct":"application\/smil","name":"smil.smil","chset":"106","cd":"attachment","cid":"<smil.smil>","cl":"smil.smil","text":"<smil><head><layout><root-layout\/>\n<region 
id=\"Image\" fit=\"meet\" top=\"0\" left=\"0\" height=\"80%\" 
width=\"100%\"\/>\n<region id=\"Text\" top=\"80%\" left=\"0\" 
height=\"20%\" width=\"100%\"\/>\n<\/layout>\n<\/head>\n<body><par 
dur=\"5000ms\"><img src=\"image0000001.jpg\" 
region=\"Image\"\/>\n<\/par>\n<par dur=\"5000ms\"><text 
src=\"text0000021.txt\" 
region=\"Text\"\/>\n<\/par>\n<\/body>\n<\/smil>\n"},{"_id":"41","mid":"18","seq":"0","ct":"image\/jpeg","name":"image0000001.jpg","cd":"attachment","cid":"<image0000001.jpg>","cl":"image0000001.jpg","_data":"\/data\/user_de\/0\/com.android.providers.telephony\/app_parts\/PART_1620739770387_image0000001.jpg"},{"_id":"42","mid":"18","seq":"0","ct":"text\/plain","name":"text0000021.txt","chset":"106","cd":"attachment","cid":"<text0000021.txt>","cl":"text0000021.txt","text":"Elle 
a bien ! "}]}
```

**Comment by tmo1** [comment] 2024-02-05 04:55
This doesn't seem to be valid (ND)JSON. Are you sure that this is exactly what SMS I/E output?

**Comment by DavidHenryThoreau** [comment] 2024-02-08 07:18
Yes, I've opened with text editor and copy/paste line 18575 and anonymize some parts.

**Comment by tmo1** [comment] 2024-02-09 15:20
I think that there may be something wrong with your copying and pasting - perhaps you added or removed spacing or line breaks? Please make sure to copy and paste exactly. To verify that you've done it correctly, [make sure it validats as JSON](https://jsonlint.com/).

**Comment by DavidHenryThoreau** [comment] 2024-03-02 13:01
Steps I've done :  
- Export SMS with sms-ie
- `jq 'del(.[].display_name)' messages-nnn.json > messages-nnn-MIUI-stripped.json`
- I'm getting `jq: error (at messages.ndjson:18580): Cannot index string with string "display_name"`
- Here's the screen output (open with mousepad text editor) 
- https://i.ibb.co/WyjpXJm/Capture-d-cran-2024-03-02-13-16-55.png

**Comment by DavidHenryThoreau** [comment] 2024-03-02 13:02
{ seems to match }

**Comment by tmo1** [comment] 2024-03-05 13:14
Again, I need actual NDJSON output from the app to troubleshoot this. Please make you're posting the **exact** output, and please check that it validates as NDJSON, as above.

**Comment by DavidHenryThoreau** [comment] 2024-03-28 08:28
I've ident it and it's ok for https://jsonlint.com/

```
{
    "_id": "18",
    "thread_id": "14",
    "date": "1620739770",
    "date_sent": "1620730823",
    "msg_box": "1",
    "read": "1",
    "m_id": "148C2480-B248-71EB-8618-0050569C3D99",
    "ct_t": "application\/vnd.wap.multipart.related",
    "ct_l": "http:\/\/2x.orange.fr\/mmsc?XCPPKPOREREJNa",
    "m_cls": "personal",
    "m_type": "132",
    "v": "18",
    "m_size": "594830",
    "pri": "129",
    "tr_id": "TOTOTO",
    "retr_st": "128",
    "retr_txt": "1000:Ok",
    "retr_txt_cs": "106",
    "d_rpt": "129",
    "locked": "0",
    "seen": "1",
    "timed": "0",
    "date_ms_part": "0",
    "deleted": "0",
    "sync_state": "0",
    "marker": "0",
    "bind_id": "0",
    "mx_status": "0",
    "need_download": "0",
    "out_time": "0",
    "preview_type": "0",
    "preview_data_ts": "0",
    "sim_id": "1",
    "block_type": "0",
    "advanced_seen": "3",
    "mx_type": "0",
    "favorite_date": "0",
    "text_only": "0",
    "__sender_address": {
        "_id": "22",
        "msg_id": "18",
        "address": "+33970580490",
        "type": "137",
        "charset": "106",
        "__display_name": "TTTïs"
    },
    "__recipient_addresses": [
        {
            "_id": "23",
            "msg_id": "18",
            "address": "+33878235890",
            "type": "151",
            "charset": "106",
            "__display_name": "oi"
        }
    ],
    "__parts": [
        {
            "_id": "40",
            "mid": "18",
            "seq": "-1",
            "ct": "application\/smil",
            "name": "smil.smil",
            "chset": "106",
            "cd": "attachment",
            "cid": "<smil.smil>",
            "cl": "smil.smil",
            "text": "<smil><head><layout><root-layout\/>\n<region id=\"Image\" fit=\"meet\" top=\"0\" left=\"0\" height=\"80%\" width=\"100%\"\/>\n<region id=\"Text\" top=\"80%\" left=\"0\" height=\"20%\" width=\"100%\"\/>\n<\/layout>\n<\/head>\n<body><par dur=\"5000ms\"><img src=\"image0000001.jpg\" region=\"Image\"\/>\n<\/par>\n<par dur=\"5000ms\"><text src=\"text0000021.txt\" region=\"Text\"\/>\n<\/par>\n<\/body>\n<\/smil>\n"
        },
        {
            "_id": "41",
            "mid": "18",
            "seq": "0",
            "ct": "image\/jpeg",
            "name": "image0000001.jpg",
            "cd": "attachment",
            "cid": "<image0000001.jpg>",
            "cl": "image0000001.jpg",
            "_data": "\/data\/user_de\/0\/com.android.providers.telephony\/app_parts\/PART_1620739770387_image0000001.jpg"
        },
        {
            "_id": "42",
            "mid": "18",
            "seq": "0",
            "ct": "text\/plain",
            "name": "text0000021.txt",
            "chset": "106",
            "cd": "attachment",
            "cid": "<text0000021.txt>",
            "cl": "text0000021.txt",
            "text": "Elle a bien ! "
        }
    ]
}
```

**Comment by tmo1** [comment] 2024-03-28 15:28
Okay - the problem is that [the `jq` invocations that I provided in issue #103](https://github.com/tmo1/sms-ie/issues/103#issuecomment-1620890135) were designed for the old `v1` format. For the current `v2` format, try the following invocations:

```
~$ jq 'del(.deleted)' messages.json > some_dir/messages.json
~$ jq 'del(. ["deleted", "sync_state"])' messages.json > some_dir/messages.json
```

**Comment by DavidHenryThoreau** [comment] 2024-03-31 09:16
The two commands don't return any errors :)
What's the next step ?

**Comment by tmo1** [comment] 2024-03-31 19:32
>  What's the next step ?

If the original export file did not contain any binary data parts (i.e., there is no `data/` directory in the Zipfile), then just run:

`~$ zip messages-fixed.zip some_dir/messages.njdson`

If there are binary parts, then navigate to the directory into which you originally unzipped the export file, then run:

`~$ zip -r messages-fixed.zip some_dir/messages.ndjson data/`

In either case, the created `messages-fixed.zip` should now be able to be imported by SMS I/E.

**Comment by DavidHenryThoreau** [comment] 2024-04-01 10:34
These two commands return a JSON file not a NDJSON : 

```
~$ jq 'del(.deleted)' messages.json > some_dir/messages.json
~$ jq 'del(. ["deleted", "sync_state"])' messages.json > some_dir/messages.json
```

I've zip them like you mentioned :
```
zip -r messages-fixed.zip messages.ndjson data/
```

I'm getting this error on MIUI 
```
can't find messages.ndjson please make sure that the provided file is a zip in the correct format
```

**Comment by tmo1** [comment] 2024-04-01 12:03
> These two commands return a JSON file not a NDJSON :

You're right - I corrected the `jq` invocations above.

> I renamed ...

> I've zip them like you mentioned ...

Looks right.

> I'm getting this error on MIUI ...

What does the Zipfile look like? (`unzip -l messages-fixed.zip`).

**Comment by DavidHenryThoreau** [comment] 2024-04-01 12:20
I've tried 
```
~$ jq 'del(.deleted)' messages.ndjson > some_dir/messages.ndjson
~$ jq 'del(. ["deleted", "sync_state"])' messages.ndjson > some_dir/messages.ndjson
```

The `messages.ndjson` is formated like 

```
{
    "_id": "18",
    "thread_id": "14",
    "date": "1620739770",
    "date_sent": "1620730823",
    "msg_box": "1",
    "read": "1",
    "m_id": "148C2480-B248-71EB-8618-0050569C3D99",
    "ct_t": "application\/vnd.wap.multipart.related",
    "ct_l": "http:\/\/2x.orange.fr\/mmsc?XCPPKPOREREJNa",
    "m_cls": "personal",
    "m_type": "132",
    "v": "18",
    "m_size": "594830",
    "pri": "129",
    "tr_id": "TOTOTO",
    "retr_st": "128",
    "retr_txt": "1000:Ok",
    "retr_txt_cs": "106",
    "d_rpt": "129",
    "locked": "0",
    "seen": "1",
    "timed": "0",
    "date_ms_part": "0",
    "deleted": "0",
    "sync_state": "0",
    "marker": "0",
    "bind_id": "0",
    "mx_status": "0",
    "need_download": "0",
    "out_time": "0",
    "preview_type": "0",
    "preview_data_ts": "0",
    "sim_id": "1",
    "block_type": "0",
    "advanced_seen": "3",
    "mx_type": "0",
    "favorite_date": "0",
    "text_only": "0",
    "__sender_address": {
        "_id": "22",
        "msg_id": "18",
        "address": "+33970580490",
        "type": "137",
        "charset": "106",
        "__display_name": "TTTïs"
    },
    "__recipient_addresses": [
        {
            "_id": "23",
            "msg_id": "18",
            "address": "+33878235890",
            "type": "151",
            "charset": "106",
            "__display_name": "oi"
        }
    ],
    "__parts": [
        {
            "_id": "40",
            "mid": "18",
            "seq": "-1",
            "ct": "application\/smil",
            "name": "smil.smil",
            "chset": "106",
            "cd": "attachment",
            "cid": "<smil.smil>",
            "cl": "smil.smil",
            "text": "<smil><head><layout><root-layout\/>\n<region id=\"Image\" fit=\"meet\" top=\"0\" left=\"0\" height=\"80%\" width=\"100%\"\/>\n<region id=\"Text\" top=\"80%\" left=\"0\" height=\"20%\" width=\"100%\"\/>\n<\/layout>\n<\/head>\n<body><par dur=\"5000ms\"><img src=\"image0000001.jpg\" region=\"Image\"\/>\n<\/par>\n<par dur=\"5000ms\"><text src=\"text0000021.txt\" region=\"Text\"\/>\n<\/par>\n<\/body>\n<\/smil>\n"
        },
        {
            "_id": "41",
            "mid": "18",
            "seq": "0",
            "ct": "image\/jpeg",
            "name": "image0000001.jpg",
            "cd": "attachment",
            "cid": "<image0000001.jpg>",
            "cl": "image0000001.jpg",
            "_data": "\/data\/user_de\/0\/com.android.providers.telephony\/app_parts\/PART_1620739770387_image0000001.jpg"
        },
        {
            "_id": "42",
            "mid": "18",
            "seq": "0",
            "ct": "text\/plain",
            "name": "text0000021.txt",
            "chset": "106",
            "cd": "attachment",
            "cid": "<text0000021.txt>",
            "cl": "text0000021.txt",
            "text": "Elle a bien ! "
        }
    ]
}
```
so it's not a NDJSON ?


The 

```
unzip -l messages-fixed.zip
```
returns a data folder and a message.ndjson

I've tried to import it to MIUI i'm getting and other values instead of sim_id it's blinking 

```
Org.jsonException value sim_id
```

**Comment by DavidHenryThoreau** [comment] 2024-04-01 12:46
I've tried 
```
~$ jq 'del(.deleted)' messages.ndjson > some_dir/messages.ndjson
~$ jq 'del(. ["deleted", "sync_state"])' messages.ndjson > some_dir/messages.ndjson
```

The `messages.ndjson` is formated like 

```
{
    "_id": "18",
    "thread_id": "14",
    "date": "1620739770",
    "date_sent": "1620730823",
    "msg_box": "1",
    "read": "1",
    "m_id": "148C2480-B248-71EB-8618-0050569C3D99",
    "ct_t": "application\/vnd.wap.multipart.related",
    "ct_l": "http:\/\/2x.orange.fr\/mmsc?XCPPKPOREREJNa",
    "m_cls": "personal",
    "m_type": "132",
    "v": "18",
    "m_size": "594830",
    "pri": "129",
    "tr_id": "TOTOTO",
    "retr_st": "128",
    "retr_txt": "1000:Ok",
    "retr_txt_cs": "106",
    "d_rpt": "129",
    "locked": "0",
    "seen": "1",
    "timed": "0",
    "date_ms_part": "0",
    "deleted": "0",
    "sync_state": "0",
    "marker": "0",
    "bind_id": "0",
    "mx_status": "0",
    "need_download": "0",
    "out_time": "0",
    "preview_type": "0",
    "preview_data_ts": "0",
    "sim_id": "1",
    "block_type": "0",
    "advanced_seen": "3",
    "mx_type": "0",
    "favorite_date": "0",
    "text_only": "0",
    "__sender_address": {
        "_id": "22",
        "msg_id": "18",
        "address": "+33970580490",
        "type": "137",
        "charset": "106",
        "__display_name": "TTTïs"
    },
    "__recipient_addresses": [
        {
            "_id": "23",
            "msg_id": "18",
            "address": "+33878235890",
            "type": "151",
            "charset": "106",
            "__display_name": "oi"
        }
    ],
    "__parts": [
        {
            "_id": "40",
            "mid": "18",
            "seq": "-1",
            "ct": "application\/smil",
            "name": "smil.smil",
            "chset": "106",
            "cd": "attachment",
            "cid": "<smil.smil>",
            "cl": "smil.smil",
            "text": "<smil><head><layout><root-layout\/>\n<region id=\"Image\" fit=\"meet\" top=\"0\" left=\"0\" height=\"80%\" width=\"100%\"\/>\n<region id=\"Text\" top=\"80%\" left=\"0\" height=\"20%\" width=\"100%\"\/>\n<\/layout>\n<\/head>\n<body><par dur=\"5000ms\"><img src=\"image0000001.jpg\" region=\"Image\"\/>\n<\/par>\n<par dur=\"5000ms\"><text src=\"text0000021.txt\" region=\"Text\"\/>\n<\/par>\n<\/body>\n<\/smil>\n"
        },
        {
            "_id": "41",
            "mid": "18",
            "seq": "0",
            "ct": "image\/jpeg",
            "name": "image0000001.jpg",
            "cd": "attachment",
            "cid": "<image0000001.jpg>",
            "cl": "image0000001.jpg",
            "_data": "\/data\/user_de\/0\/com.android.providers.telephony\/app_parts\/PART_1620739770387_image0000001.jpg"
        },
        {
            "_id": "42",
            "mid": "18",
            "seq": "0",
            "ct": "text\/plain",
            "name": "text0000021.txt",
            "chset": "106",
            "cd": "attachment",
            "cid": "<text0000021.txt>",
            "cl": "text0000021.txt",
            "text": "Elle a bien ! "
        }
    ]
}
```
so it's not a NDJSON ?


The 

```
unzip -l messages-fixed.zip
```
returns a data folder and a messages.ndjson

I've tried to import it to MIUI i'm getting and other values instead of sim_id it's blinking 

```
Org.jsonException value sim_id
```

**Comment by DavidHenryThoreau** [comment] 2024-06-12 06:23
Can you reproduce that error ?

**Comment by tmo1** [comment] 2024-06-14 14:14
I'll take a look when I get a chance.
