### ISSUE TITLE
SMS Import/Export no longer shows up as selection in Default SMS App list  (Graphene OS 2024030800  Android Pixel 6)

### ISSUE THREAD

**Issue by PaulAGH** [tmo1/sms-ie#169] opened 2024-03-12 05:19 UTC
I recently installed SMS Import/Export 2.3.1 on a Pixel 6 with a new installation of Graphene OS 2024030300.  I was able to make it the default SMS app, and it did a great job exporting the SMS/MMS messages.  A few days later, I installed Graphene OS 2024030900 on a Pixel 7, and after installing SMS Import/Export, I was not able to make it the default SMS app, as it did not show up in the selection.  I tried rebooting, and all sort of things to see if I could do something to make it appear in the list, and none of it worked.  The Pixel 6 device was then automatically updated to Graphene OS 2024030800, and following the update, the SMS Import/Export no longer appeared in the Default SMS App list as it did when the Pixel 6 was running Graphene OS 2024030300.  If SMS Import/Export is not able to be made the default SMS App, then it is not able to import/export SMS messages.

**Comment by tmo1** [comment] 2024-03-12 12:16
Duplicate of #167 - this has been fixed in v2.3.2.

**Closed** 2024-03-12 12:17 UTC

**Comment by PaulAGH** [comment] 2024-03-15 03:38
The rapid response was much appreciated.  Nice work!

**Comment by tmo1** [comment] 2024-03-15 20:35
> The rapid response was much appreciated. Nice work!

Thank you! But credit where credit is due: [the fix was actually contributed by one of the earlier reporters](https://github.com/tmo1/sms-ie/pull/168).
