### ISSUE TITLE
Error when importing sms

### ISSUE THREAD

**Issue by farzadx** [tmo1/sms-ie#103] opened 2023-03-11 12:21 UTC
Hi
When i import messages i get error
My phone is poco x3 pro 
Android 12

![Screenshot_2023-03-11-15-48-58-316_com github tmo1 sms_ie](https://user-images.githubusercontent.com/70059397/224484227-d0113590-9214-44eb-8265-cc10cc603d66.png)

**Comment by tmo1** [comment] 2023-03-12 04:56
https://github.com/tmo1/sms-ie#posting-json
https://github.com/tmo1/sms-ie#crashes

**Comment by farzadx** [comment] 2023-03-12 19:27
[logs.txt](https://github.com/tmo1/sms-ie/files/10951813/logs.txt)

**Comment by farzadx** [comment] 2023-03-12 19:38
[messages-2023-03-12.json.txt](https://github.com/tmo1/sms-ie/files/10951851/messages-2023-03-12.json.txt)

**Comment by tmo1** [comment] 2023-03-13 01:26
Thank you - I'm looking into this.

**Comment by tmo1** [comment] 2023-03-15 17:25
I can't find any trace of the error message you're seeing online, but I hope I can fix the problem. I have something I'll try  when I get a chance.

**Comment by tmo1** [comment] 2023-03-21 01:33
I have been unable to reproduce the problem using the JSON file you provided on various (emulated) Android images, including an Android 12 (API 31) one - in my tests, the two SMS messages import correctly, without error. Is your Poco X3 Pro using MIUI, or something closer to stock Android, like LineageOS?

**Comment by farzadx** [comment] 2023-03-22 16:12
Miui

**Comment by tmo1** [comment] 2023-03-23 01:43
If the problem can't be reproduced on regular Android, there's not much I can do to troubleshoot. Just guessing from the error message (about which I can't find anything online, as above, perhaps because it's not a standard Android error message), you might try removing the `"deleted": "0"` lines from the JSON and seeing if that lets the improt work. If it does, I can provide a script or jq invocation that automates the process.

**Comment by farzadx** [comment] 2023-03-24 21:53
I recover my messages with other phone, ok i will try , thanks

**Comment by tmo1** [comment] 2023-07-05 01:23
> I had similar issue on miui 14. After I deleted "deleted 0" and "sync state 0" completely from the file on the latest beta 2.0 pre version, I was able to restore my SMS.

Thank you for the report. I plan to document this problem and solution in the README and close this issue.

FTR, removing all the `deleted` keys from the JSON can be done with the [jq](https://jqlang.github.io/jq/) tool:
```
~$ jq 'del(.[].display_name)' messages-nnn.json > messages-nnn-MIUI-stripped.json
```
where `messages-nnn.json` is the name of the original JSON file, and `messages-nnn-MIUI-stripped.json` is a file to write the stripped JSON to.

To remove both the `deleted` and `sync_state` keys, run:
```
~$ jq 'del(.[] ["deleted", "sync_state"])' messages-nnn.json > messages-nnn-MIUI-stripped.json
```

**Closed** 2023-07-05 01:40 UTC
Labels: bug

**Comment by viktak** [comment] 2024-11-13 08:10
Hi and thanks for this great tool!
I got to this page as I got the same error on a MIUI device. I tried the workaround described above, but it did not work. To be honest, The command suggested above (`jq 'del(.[] ["deleted", "sync_state"])' messages-nnn.json > messages-nnn-MIUI-stripped.json`) errored out for me, so I had to modify it.
It worked like this for me:
`cat ./messages.ndjson | jq 'del(.deleted, .sync_state)' > messages.ndjson-MIUI-stripped.json`
(Just writing it here, so that you can correct me if I made a mistake I don't realize.)

The result I'm getting is a proper json file, here is an example entry:
```
{
  "_id": "1",
  "thread_id": "10",
  "date": "1583918765",
  "date_sent": "1583918765",
  "msg_box": "1",
  "read": "1",
  "sub": "",
  "sub_cs": "106",
  "m_type": "132",
  "ct_cls": "135",
  "locked": "0",
  "seen": "1",
  "timed": "0",
  "date_ms_part": "0",
  "marker": "0",
  "bind_id": "0",
  "mx_status": "0",
  "need_download": "0",
  "out_time": "0",
  "preview_type": "0",
  "preview_data_ts": "0",
  "sim_id": "-1",
  "block_type": "0",
  "advanced_seen": "3",
  "mx_type": "0",
  "favorite_date": "0",
  "text_only": "0",
  "__sender_address": {
    "_id": "1",
    "msg_id": "1",
    "address": "aaaaaaaaaaaaaa",
    "type": "137",
    "charset": "106"
  },
  "__recipient_addresses": [
    {
      "_id": "2",
      "msg_id": "1",
      "address": "lkjhlkjhlkj@kjhlkjhlkjh.com",
      "type": "151",
      "charset": "106"
    }
  ],
  "__parts": [
    {
      "_id": "1",
      "mid": "1",
      "seq": "0",
      "ct": "application/vnd.gsma.botmessage.v1.0+json",
      "name": "attachment",
      "chset": "106",
      "_data": "/data/user_de/0/com.android.providers.telephony/app_parts/PART_1583918766283"
    }
  ]
}
```
When I try to import this I get an error for pretty much everything, like this:
![Screenshot_2024-11-13-09-59-52-850_com github tmo1 sms_ie](https://github.com/user-attachments/assets/cc5ad967-90bc-4b64-94be-8d8e97ab0887)

or this:
![Screenshot_2024-11-13-09-59-56-970_com github tmo1 sms_ie](https://github.com/user-attachments/assets/f4508532-bdd2-40e7-b063-1381139b0c34)

Since it looks like a total disaster, I suspect it has to do with the tools I use. So here is my "toolchain":

- I do the conversion on Linux in a docker container: Debian GNU/Linux 11 (bullseye) x86_64
- jq version: jq-1.6
- I do the zip/unzip operation on a Windows 11 64-bit box

Any idea what could be wrong?

**Comment by tmo1** [comment] 2024-11-14 13:05
> Any idea what could be wrong?

I think the problem is that the original jq command I gave (and your modification thereof) are emitting normal JSON, and the current `v2` format requires NDJSON. Try adding the `-c` flag to jq.

**Comment by viktak** [comment] 2024-11-14 16:26
Thanks for the quick reply. I'll try this, but only on Tuesday, as I'm away at the moment. Will report back!

**Comment by viktak** [comment] 2024-11-15 18:13
Thank you for the quick reply. I'm away now, so can't try this until Tuesday. I will report back then.
