### ISSUE TITLE
[Feature request] Calls deduplication

### ISSUE THREAD

**Issue by ngocanhtve** [tmo1/sms-ie#189] opened 2024-06-06 09:20 UTC
Dear,

Now the message deduplication feature is working well, would you consider adding the feature to call logs?

Thanks!

**Comment by tmo1** [comment] 2024-06-06 12:21
Duplicate of #176

**Comment by tmo1** [comment] 2024-06-06 12:21
[This has already been implemented](https://github.com/tmo1/sms-ie/commit/69d2f95b9b1f0eb41168330707cf9f47f2004e5e), and will be available in the next release, which I hope to push within a day or two.

**Closed by tmo1** 2024-06-06 12:21 UTC

**Comment by ngocanhtve** [comment] 2024-06-12 01:53
It worked. Thank!

**Comment by tmo1** [comment] 2024-06-17 20:57
> It worked. Thank!

You're welcome! Thanks for your translation work.
