### ISSUE TITLE
Crash when importing .json file

### ISSUE THREAD

**Issue by thfi** [tmo1/sms-ie#14] opened 2022-01-06 15:59 UTC
When importing a .json file made as a backup on another phone, SMS Import/Export 1.3 (installed via F-Droid) immediately crashes without any error message.
Using a custom ROM (crdroid), I get this error log:

```
time: 1641484413465
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getAuthority()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getAuthority()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
	at android.content.ContentResolver.insert(ContentResolver.java:2149)
	at android.content.ContentResolver.insert(ContentResolver.java:2111)
	at com.github.tmo1.sms_ie.MainActivity$importJson$2.invokeSuspend(MainActivity.kt:519)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by tmo1** [comment] 2022-01-06 17:52
Thanks for reporting this - it's probably a duplicate of #11 and #12, in which case it has already been fixed in the repository. The next release will contain the fix, and in the meantime an APK is available [here](https://github.com/tmo1/sms-ie/files/7808122/sms-ie-ignore-absent-fields.zip).

**Comment by tmo1** [comment] 2022-01-06 17:52
Duplicate of #11, #12

**Comment by tmo1** [comment] 2022-01-06 17:53
Duplicate of #11

**Comment by tmo1** [comment] 2022-01-06 17:53
Duplicate of #12

**Closed** 2022-01-06 17:53 UTC
Labels: bug
